name: Build Linux App

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Linux AppImage & tar.gz
        run: npm run build:linux

      - name: List build output
        run: ls -lhR dist/

      - name: Upload artifact (AppImage or tar.gz)
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/

      - name: Upload to GitHub Release (only if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
