name: Build (Linux x64)

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v4

      # 1. 优先手动安装 pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm@8
          echo "PATH=$(npm root -g)/bin:$PATH" >> $GITHUB_ENV

      # 2. 设置 Node.js（仅用于版本管理和缓存）
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      # 3. 验证环境
      - name: Check pnpm
        run: |
          pnpm --version
          which pnpm

      # 4. 正常构建流程
      - run: pnpm install --frozen-lockfile
      - run: pnpm build:linux
      - run: ls -R dist
