name: Build (Linux x64)

on:
  push:
    tags: v*  # 仅当推送 tag 时触发（格式 v*，如 v1.0.0）
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Linux 环境
    env:
      NODE_OPTIONS: --max-old-space-size=4096  # 防止内存不足

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 使用最新版本

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x  # 指定 Node.js 版本
          cache: 'pnpm'  # 缓存 pnpm 依赖

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # 指定 pnpm 版本

      - name: Install dependencies
        run: pnpm install --frozen-lockfile  # 严格锁定依赖版本

      - name: Build for Linux x64
        run: pnpm run build:linux:x64  # 替换为你的实际构建命令

      - name: List dist files (调试用)
        run: ls -R dist  # 查看生成的构建文件

      - name: Upload release assets (可选)
        if: startsWith(github.ref, 'refs/tags/')  # 仅在 tag 推送时上传
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.deb      # 如果有 deb 包
            dist/*.AppImage # 如果有 AppImage
            dist/*.tar.gz   # 其他 Linux 包
          draft: false
          prerelease: false
